### PR TITLE
Add docker files

### LINKED ISSUE #5: Add Docker configurations
**Is your feature request related to a problem? Please describe.**
Add `Dockerfile` and `docker-compose.yml` files. This will help with development and running the application in the correct environment.

**Describe the solution you'd like**
Add the following files:
* Dockerfile
* docker-compose.yml

**Describe alternatives you've considered**
N/A

**Additional context**
Docker will make using this project easier for new users. It will also provide a sandbox way to run the project without much Node.js knowledge.

### PR DESCRIPTION
**Pull request by froi**
So you're you want to submit a Pull Request? __Thank you!__

Before you submit it please check that a similar PR has not been submitted. You can do a quick search here: [Pull request](https://github.com/GSA/code-gov-harvester/pulls).

If one has not been submitted please fill out the following information so we can understand and work with your PR.

For more information, see our [CONTRIBUTING](https://github.com/GSA/code-gov-harvester/blob/master/docs/CONTRIBUTING.md) guide.

----

## Summary

Added Docker files to help in the development and deployment of the project.

## This PR fixes/implements the following **bugs/features**

* [x] Feature #5 

## Motivation 

As explained in issue #5 having the Docker and docker-compose files will help new users play with the project. In addition having these files can help with development and deployment of the project.

## Tests
To my knowledge there isn't a automated way to test these files. I've added a screenshot of the `docker-compose` command running.

image

## Code formatting

Linting error was beyond scope of this PR but was fixed;

image

## Closing issues

Closes #5

### CODE REVIEW

**Comment by seanstar12** [comment]
Looks good, but can you update the docker instructions to the [README](https://github.com/froi/code-gov-harvester/blob/add-docker-files/README.md) as well?

Could be as simple as:
```
npm install
docker-compose up
```
Or could be copied from [code-gov-api](https://github.com/GSA/code-gov-api/#docker-compose).

**Comment by froi** [comment]
@seanstar12 Done.

**Comment by froi** [comment]
Hi peeps.

@saracope @seanstar12 can this be merged or closed. I'd like to start cleaning out the PR I have in progress.

Thanks

**Comment by froi** [comment]
@saracope 

I'm closing this PR. At this point it's stale and I would like to get it off my list.

**Comment by jcastle-zz** [comment]
Thanks @froi!

**Pull request closed without merging**
